framely/community

docs/.vuepress/styles/index.scss

update story css

---

docs/.vuepress/config.ts
package.json
yarn.lock

theme change

---

docs/.vuepress/components/homefooter/homefooter.vue
docs/.vuepress/config.ts
docs/.vuepress/styles/index.scss

homefooter added

---

docs/.vuepress/config.ts
docs/.vuepress/public/manifest.webmanifest

fix theme-color, works good on iOS, not sure about Android

fix-theme-color

---

docs/.vuepress/components/page/Page.vue
docs/.vuepress/styles/index.scss
docs/reference/annotations/vr.md

move-vuepresstoc-to-indexscss

---

docs/reference/annotations/confirmation.md
docs/reference/framefilling.md
docs/reference/systemframes/systemframe.md

- add toc
- fix use case format
- fix 404

Yigexu patch 1

---

docs/reference/annotations/fillstrategy.md

- change slot filling phase name to make it consistent
- add a few missing VC

fix fill strategy

---

docs/.vuepress/styles/index.scss

How to use see >> https://naturali-io.feishu.cn/docx/doxcn4OFKuMMf4SjXX8u9Mz9X9g

add-thumbnnail-container

---

docs/.vuepress/styles/index.scss

after this, we can use markdown in conversation containers, but have to use conversation+user+bot together

fixed conversation containers

---

docs/reference/systemframes/systemframe.md

add slot update for system intent

Piece of System intent: SlotUpdate

---

docs/guide/glossary.md
docs/reference/providers/extension.md
docs/reference/systemframes/systemframe.md

1. Optimized glossary format;
2. Update content, like version control, function description, fill strategy;
3. Add auto completion, initialization;
4. Move "System CUI Components" from Glossary to System CUI Components, because the content is not the glossary of terms, it is the motivation of system components.

update glossary and system CUI components

---

docs/.vuepress/components/hero/hero.vue
docs/.vuepress/components/homefooter/homefooter.vue
docs/.vuepress/components/page/footer.vue
docs/.vuepress/config.ts
docs/.vuepress/configs/navbar/en.ts
docs/.vuepress/theme/layouts/Article.vue
docs/reference/platform/signingup.md

change-to-opencui

---

docs/reference/annotations/systemcomponent.md

Add system cui

---

docs/guide/quickstart-reservation.md

fix Ordered Lists

---

docs/guide/pingpong.md
docs/guide/quickstart-channel.md
docs/guide/quickstart-reservation.md
docs/guide/start-with-clone.md

Follow [Before we start](https://naturali-io.feishu.cn/docx/Th6adgJAjoTq7Zx4TA5cx0yknBb?source_type=message&from=message) to add before-you-start
1. Clone and Modify
2. Quickstart with PingPong
3. Interactions with Channels
4. Table Reservation

add before-you-start

---

docs/guide/quickstart-reservation.md

add before-you-start back

---

docs/guide/pingpong.md

fix pingpong.md

---

docs/articles/index.md

等 build-reservation-module 改好了，再 expose

hide build-reservation-module.md (for now)

---

docs/.vitepress/configs/sidebar/en.ts
docs/index.md

Reverts framely/community#1224

Revert "Update index.md"

---

docs/copilot/build-copilot.md

1. 有些在 md 中换行的 line 在网页显示上也换行了，当前 pr 将这些不该换行的 line 合并成了一行 （举例如下图所示）
2. 修复了一些语法方面的问题

fix build-copilot.md

---

docs/components/video/videoSection.vue
docs/index.md

When add homepage video section, use this format in index.md：
```
video :
- link: videos/dhl_1015.mp4
```

Add video component

---

docs/components/video/videoSection.vue
docs/index.md

根据之前的讨论，暂时移除了 autoplay 和 loop，添加了 controls

Upload video of introduction
